on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  build-arr-app:
    strategy:
      fail-fast: true
      matrix:
        include:
          - arr-app: "radarr"
            branch: "master"
          - arr-app: "sonarr"
            branch: "main"
          - arr-app: "lidarr"
            branch: "develop"
          - arr-app: "readarr"
            branch: "develop"
    uses: ./.github/workflows/build-arr-docker-image-if-necessary.yml
    with:
      arr-app: ${{ matrix.arr-app }}
      branch: ${{ matrix.branch }}
    secrets: inherit
