on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  get-radarr-version:
    runs-on: ubuntu-22.04
    outputs:
      radarr-version: ${{ steps.radarr-version-step.outputs.LATEST_RADARR_VERSION }}
      should-build: ${{ steps.radarr-version-step.outputs.SHOULD_BUILD }}
    steps:
      - run: >-
          echo LATEST_RADARR_VERSION=$(
          git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/Radarr/Radarr.git
          | tail -n1
          | sed 's/.*\///; s/\^{}//'
          )
          | tee -a "$GITHUB_ENV" "$GITHUB_OUTPUT"
      - run: >-
          docker manifest inspect "docker.io/guillaumedsde/radarr-distroless:${LATEST_RADARR_VERSION}" 
          || echo SHOULD_BUILD=1 >> "$GITHUB_OUTPUT"

  docker:
    needs: get-radarr-version
    if: ${{ needs.get-radarr-version.outputs.should-build == '1' }}
    uses: guillaumedsde/qbittorrent-distroless/.github/workflows/docker.yml@master
    with:
      software-version: ${{ needs.get-radarr-version.outputs.radarr-version }}
      platforms: |
        linux/amd64
        linux/arm64
    secrets: inherit
